### ISSUE TITLE
imported css file build error

### ISSUE THREAD

**Issue by imjuni** [reactql/cli#43]
I want install [blueprint.js](http://blueprintjs.com/). After I import blueprint.css, see below.

```
// in app.tsx
// React
import * as React from 'react';
import { SFC } from 'react';

// Routing
import {
  match,
  Link,
  Route,
  RouteComponentProps,
  Switch,
} from 'react-router-dom';

// <Helmet> component for setting the page title
import Helmet from 'react-helmet';

import {compose, pure} from 'recompose';

// NotFound 404 handler for unknown routes
import { NotFound } from 'kit/lib/routing';

// Styles
import './styles.global.css';
import '@blueprintjs/core/dist/blueprint.css';   // import blueprint.css
```

I expect that code work well. But I've got error.

```
// Error
/Users/imjuni/Project/[project_path]/node_modules/@blueprintjs/core/dist/blueprint.css:1
(function (exports, require, module, __filename, __dirname) { @charset "UTF-8";
                                                              ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/imjuni/Project/company/yanolja-joy-admin/dist/server_dev.js:773:18)
    at __webpack_require__ (/Users/imjuni/Project/company/yanolja-joy-admin/dist/server_dev.js:20:30)

[at-loader] Checking started in a separate process...
```

I guess that is caused from node_module. (Usually JavaScript parser meet css file, raised that error).    But configuration already describe externals.

```
// server.js
externals: [
    nodeModules(),
  ],
```

What is missed? Can you help me?

**Comment by leebenson** [comment]
Put the external CSS in your `styles.global.css` file, and then import it with the `~` character to signify that it's in `node_modules`:

**styles.global.css**
```css
@import '~@blueprintjs/core/dist/blueprint.css';
```
This will also have the effect of preserving classnames, which is what Blueprint requests.

**Comment by imjuni** [comment]
@leebenson Thank you for your answer. Can I know what configuration affect that?

**Comment by leebenson** [comment]
@imjuni - see https://github.com/reactql/kit/blob/master/kit/webpack/common.js#L49-L50

Whenever you use `*.global.(css|scss|sass|less`, classnames will be preserved.
