### ISSUE TITLE
Issue with docker build

### ISSUE THREAD

**Issue by justinhandley** [reactql/cli#51]
I'm running into issues with the docker build.  On a completely blank install - just ran reactql new, then docker build . -t projectname - and I'm getting this.

```
Step 8/11 : RUN npm run build
 ---> Running in d725d4598e1c

> biz2biz_ra@1.15.1 build /src
> cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors

(node:24) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Child
    Hash: 87d237d27a0c2dd244c8
    Time: 10357ms
    
    ERROR in chunk manifest [entry]
    [name].[chunkhash].js
    Chunk.entry was removed. Use hasRuntime()
    Error: Chunk.entry was removed. Use hasRuntime()
        at Chunk.get entry [as entry] (/src/node_modules/webpack/lib/Chunk.js:49:9)
        at registerChunk (/src/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:28:73)
        at Array.reduce (native)
        at registerChunk (/src/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:36:27)
        at Array.reduce (native)
        at MainTemplate.<anonymous> (/src/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:25:33)
        at MainTemplate.applyPluginsWaterfall (/src/node_modules/webpack/node_modules/tapable/lib/Tapable.js:92:24)
        at MainTemplate.plugin (/src/node_modules/webpack/lib/MainTemplate.js:106:31)
        at MainTemplate.applyPluginsWaterfall (/src/node_modules/webpack/node_modules/tapable/lib/Tapable.js:92:24)
        at MainTemplate.render (/src/node_modules/webpack/lib/MainTemplate.js:175:31)
        at Compilation.createChunkAssets (/src/node_modules/webpack/lib/Compilation.js:1254:34)
        at sealPart2 (/src/node_modules/webpack/lib/Compilation.js:629:10)
        at next (/src/node_modules/webpack/node_modules/tapable/lib/Tapable.js:184:11)
        at /src/node_modules/extract-text-webpack-plugin/dist/index.js:241:13
        at /src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
        at iteratorCallback (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
        at /src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
        at /src/node_modules/extract-text-webpack-plugin/dist/index.js:224:15
        at /src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
        at eachOfArrayLike (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:991:9)
        at eachOf (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1051:5)
        at Object.eachLimit (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3145:5)
        at /src/node_modules/extract-text-webpack-plugin/dist/index.js:189:29
        at /src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3083:16
        at eachOfArrayLike (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1003:9)
        at eachOf (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1051:5)
        at Object.eachLimit (/src/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3145:5)
        at Compilation.<anonymous> (/src/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
        at Compilation.applyPluginsAsyncSeries (/src/node_modules/webpack/node_modules/tapable/lib/Tapable.js:188:13)
        at Compilation.seal (/src/node_modules/webpack/lib/Compilation.js:579:8)
Child
       42 modules

Couldn't parse bundle asset "/src/dist/public/browser.94235cfb9483ffed8e65.js".
Analyzer will use module sizes from stats file.

Webpack Bundle Analyzer saved report to /src/dist/report.html
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! biz2biz_ra@1.15.1 build: `cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the biz2biz_ra@1.15.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-25T17_20_14_715Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 2

```

**Comment by leebenson** [comment]
I'm not able to replicate this issue on a blank install with CLI v3.7.1 (kit v1.15.1). Which version of the kit are you using?

**Comment by leebenson** [comment]
I'll close this for now, since I'm not able to replicate locally in any recent ReactQL kit version on macOS Sierra (or High Sierra.)

If you have any more information, feel free to share and re-open.
