### ISSUE TITLE
reactql SyntaxError

### ISSUE THREAD

**Issue by edolyne** [reactql/cli#65]
I installed the CLI tool, and when running any `reactql` commands I receive a Syntax Error

I'm running node version 6.10.0 via NVM

```
 ~ reactql help
/Users/****/.nvm/versions/node/v6.10.0/lib/node_modules/reactql/cli/index.js:315
            );
            ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/****/.nvm/versions/node/v6.10.0/lib/node_modules/reactql/bin/reactql:2:1)
    at Module._compile (module.js:570:32)
```

**Comment by leebenson** [comment]
ReactQL requires Node >7.6 due to its native user of async/await on the server side. Bump your local version.
