### ISSUE TITLE
reactql new issue

### ISSUE THREAD

**Issue by Nhiokh** [reactql/cli#66]
Hi there,

OS: Windows 10

I seem to have installed reactql cli succesfully, but eveytime I try to run reactql new, it prompt this : 

```
C:\Users\Samuel\Desktop\lalala>reactql new
C:\Users\Samuel\AppData\Roaming\npm\node_modules\reactql\cli\index.js:315
            );
            ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Samuel\AppData\Roaming\npm\node_modules\reactql\bin\reactql:2:1)
```

Did I miss something?

**Comment by Nhiokh** [comment]
Ok... silly me. Just figured out I've got Node v6.4.

Sorry for bugging you with that.

**Comment by leebenson** [comment]
np @Nhiokh, happy to help
