### ISSUE TITLE
white space / typo preventing setup

### ISSUE THREAD

**Issue by stephanMettler** [reactql/cli#68]
Hi, 

```js
/node_modules/reactql/cli/index.js:316
            );
            ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

+ reactql@4.5.5
+ uninstall@0.0.0

 rm -r /usr/local/bin/reactql /usr/lib/node_modules/reactql/bin/reactql

yarn add reactql@latest
 ./node_modules/reactql/bin/reactql new test ....


.../node_modules/reactql/cli/index.js:316
```
...same error after clean + local install ! 

Fixed by removing a couple of whitespaces! ~16
Thank you!!

**Comment by leebenson** [comment]
Related to #67 - I presume you're using an older version of Node?

**Comment by leebenson** [comment]
Fix released in 4.5.6 - upgrade with `npm i -g reactql`

**Comment by stephanMettler** [comment]
```
yarn 6.24.1
node -v  v7.7.2
npm -version 5.3.0
```

**Comment by leebenson** [comment]
The dangling comma is a ES2017 feature introduced in Node 8, whereas the kit itself works in >= Node 7.6, so I've gone ahead and removed that from the CLi and fixed it in 4.5.6

**Comment by stephanMettler** [comment]
# We have lift off! 🚀

Graphiql out of the box and a lightning fast front-end!
support in 9 min ;) thx!

npm  5.3.0
node 8.4.0

**Comment by leebenson** [comment]
My pleasure @stephanMettler, glad it's working for you!
