### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by JamesSingleton** [reactql/cli#79]
Hello,

So this is the first time that I am using the ReactQL CLI and followed the instructions on how to install and start it. However, when I run npm start, I get the following error in GIT Bash
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration[0].entry['browser'] should be a string.
    * configuration[0].entry['browser'] should NOT have duplicate items (items ## 1 and 3 are identical) ({
        "keyword": "uniqueItems",
        "dataPath": "[0].entry['browser']",
        "schemaPath": "#/definitions/common.nonEmptyArrayOfUniqueStringValues/uniqueItems",
        "params": {
          "i": 3,
          "j": 1
        },
        "message": "should NOT have duplicate items (items ## 1 and 3 are identical)",
        "schema": true,
        "parentSchema": {
          "items": {
            "minLength": 1,
            "type": "string"
          },
          "minItems": 1,
          "type": "array",
          "uniqueItems": true
        },
        "data": [
          "E:\\Coding\\SandBox\\reactql-tutorial\\node_modules\\webpack-dev-server\\client\\index.js?http://localhost:8080",
          "webpack/hot/dev-server",
          "E:\\coding\\sandbox\\reactql-tutorial\\node_modules\\webpack-dev-server\\client\\index.js?http://localhost:8080",
          "webpack/hot/dev-server",
          "react-hot-loader/patch",
          "webpack-dev-server/client?http://localhost:8080/",
          "webpack/hot/only-dev-server",
          "E:\\coding\\sandbox\\reactql-tutorial\\kit\\entry\\browser.js"
        ]
      }).
      [non-empty string]
    * configuration[0].entry['browser'] should be one of these:
      non-empty string | [non-empty string]
    * configuration[0].entry should be a string.
    * configuration[0].entry should be an array:
      [non-empty string]
    * configuration[0].entry should be an instance of function
      function returning an entry object or a promise..
```

Is there something I am missing? Even when I run npm install in the folder I created it gives me an error as well

```
$ npm install

> node-zopfli@2.0.2 install E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.7.0 (node-v57 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at E:\Coding\SandBox\reactql-tutorial\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Coding\\SandBox\\reactql-tutorial\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\coding\\sandbox\\reactql-tutorial\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=E:\\coding\\sandbox\\reactql-tutorial\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Coding\SandBox\reactql-tutorial\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Coding\\SandBox\\reactql-tutorial\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli
node-pre-gyp ERR! node -v v8.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
npm WARN enzyme-adapter-react-16@1.0.2 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.0.5 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-zopfli@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James Singleton\AppData\Roaming\npm-cache\_logs\2017-10-23T04_45_01_991Z-debug.log
```

Any help would be greatly appreciated as all I have done is installed reactql globally and ran reactql new.

npm version: 5.4.2
node version: 8.7.0

**Comment by leebenson** [comment]
The `npm install` error is due to missing Python (>v2.7 needed). `node-zopfli` needs it to compile the extension. That should fix it.

The Webpack config error, I've never come across.  I need to test it on Windows and see what's happening. Which version of ReactQL are you using? (`reactql version`)

**Comment by JamesSingleton** [comment]
Hi @leebenson,

I have reactql version 4.9.5 (I installed it same day I created the issue). As for the python, I have python 3.6.2 on my machine.

**Comment by leebenson** [comment]
The Python error relates to this line:

> Can't find Python executable "C:\Program Files\Python36\python.EXE", you can set the PYTHON env variable.

**Comment by JamesSingleton** [comment]
Got it, what about the other part? Or could this be the overall cause?

**Comment by leebenson** [comment]
Not sure... let me know how you get on, and I'll test on Windows if necessary.

**Comment by JamesSingleton** [comment]
I only work on a Windows machine. I will check this later to see if I can figure it out to see if it is the Python issue or not. However, I feel like installing the cli and doing reactql new would of surfaced the npm install issue.

**Comment by JamesSingleton** [comment]
@leebenson,

So I did  npm config set python 'c:/program files/python36/python.exe' to set it. Now when I run npm install inside the reactql project I created, this is the error I get now:

```
$ npm install

> node-zopfli@2.0.2 install E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.2-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.2 and node@8.7.0 (node-v57 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetF                                                                                                                                                                                               rameworkVersion or PlatformToolset may be set to an invalid version number. [E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\build\zopfli.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\build\zopfli.vc                                                                                                                                                                                               xproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Coding\\SandBox\\reactql-tutorial\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--mo                                                                                                                                                                                               dule=E:\\coding\\sandbox\\reactql-tutorial\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=E:\\coding\\sand                                                                                                                                                                                               box\\reactql-tutorial\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli
gyp ERR! node -v v8.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\bin\node-gyp.js build --fallback                                                                                                                                                                                               -to-build --module=E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\coding\sandb                                                                                                                                                                                               ox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\Coding\SandBox\reactql-tutorial\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Coding\\SandBox\\reactql-tutorial\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback                                                                                                                                                                                               -to-build"
node-pre-gyp ERR! cwd E:\coding\sandbox\reactql-tutorial\node_modules\node-zopfli
node-pre-gyp ERR! node -v v8.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\Coding\SandBox\reactql-tutorial\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\coding\sa                                                                                                                                                                                               ndbox\reactql-tutorial\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=E:\coding\sandbox\reactql-tutorial\node_module                                                                                                                                                                                               s\node-zopfli\lib\binding\node-v57-win32-x64' (1)
npm WARN enzyme-adapter-react-16@1.0.2 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.0.5 requires a peer of less@^2.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-zopfli@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-zopfli@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\James Singleton\AppData\Roaming\npm-cache\_logs\2017-10-26T03_24_20_588Z-debug.log
```

**Comment by Kamill90** [comment]
@JamesSingleton have you solved this problem? 
I have the same one on my main laptop and literally no idea how to overcome it.

**Comment by leebenson** [comment]
Try http://landinghub.visualstudio.com/visual-cpp-build-tools

`CL.exe` is a C++ compiler for Windows. If you're getting that error, you probably don't have it installed.

**Comment by Kamill90** [comment]
I did. 
Also I've walked through all node-gyp node-zopfli pre-gyp atc issues. 
in reactQL project I cannot install any dependency. In other project there is no problem. Is there something wrong in package.json / kit setup? 
I use windows 10 
node 8.9
node-pre-gyp -v v0.6.38

I literally have no idea what to do.

**Comment by corydeppen** [comment]
I've run into this same issue on Win10 using Node 8.9.4 and have spent hours going through dozens of issues and different installs. I think it's unfortunate that folks have to go through this much effort to get slightly better compression on a set of files. I'll gladly take a slight bump in file size if I can remain productive and not get stuck on issues like this. The node-zopfli library seems to be abandoned, there's been an open PR for months to get it to Node 8, and there are a ton of folks hitting this same issue across various projects. Seems like it might be a good time to consider alternatives.

**Comment by leebenson** [comment]
If your system doesn't have the required build tools, this will fail - period. No getting around that, since Zopfli uses a binary to compress assets.

If you don't want/need asset compression, take the Zopfli plugin [out of your kit/webpack/browser_prod.js config](https://github.com/reactql/kit/blob/master/kit/webpack/browser_prod.js#L128-L134)

It's a 5 second fix.
