### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by ParishKhan** [reactql/cli#85]
1) I have downloaded the cli on my windows 10 64bit machine. 
2) started a new project with "**reactql new**" command.
3) then run "**npm start**" to start dev server.

But it's showing this error to the browser. I didn't touch any files. 

=========================================
Failed to compile.

(undefined) ./node_modules/css-loader?{"minimize":false,"localIdentName":"[local]-[hash:base64]","importLoaders":1,"sourceMap":true,"modules":true}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./src/components/stats.scss
Module build failed: Error: \\?\E:\Personal\ReactQL\reactql-app\node_modules\node-sass\vendor\win32-x64-59\binding.node is not a valid Win32 application\\?\E:\Personal\ReactQL\reactql-app\node_modules\node-sass\vendor\win32-x64-59\binding.node
    at Object.Module._extensions..node (module.js:670:18)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at module.exports (E:\Personal\ReactQL\reactql-app\node_modules\node-sass\lib\binding.js:19:10)
    at Object.<anonymous> (E:\Personal\ReactQL\reactql-app\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:641:30)
    at Module._extensions..js (module.js:652:10)
 @ ./src/components/stats.scss 4:14-247 18:2-22:4 19:20-253
 @ ./src/components/stats.js
 @ ./src/components/main/index.js
 @ ./src/app.js
 @ ./kit/entry/browser.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080/ webpack/hot/only-dev-server ./kit/entry/browser.js

**Comment by leebenson** [comment]
run `npm rebuild`
